### ISSUE TITLE
`openstack/configure` script fails when using `openstackclients` from snap

### ISSUE THREAD

**Issue by nicolasbock** [canonical/stsstack-bundles#51]
When the `openstackclients` are installed via snap, the Python libraries shipped with the snap are not in the `PYTHONPATH` and consequently Python scripts called from `configure` fail as for example:

```console
+ ./bin/neutron-ext-net-ksv3 --project admin --network-type flat -g 10.5.0.1 -c 10.5.0.0/16 -f 10.5.150.0:10.5.200.254 ext_net
Traceback (most recent call last):
  File "./bin/neutron-ext-net-ksv3", line 3, in <module>
    from keystoneclient.auth import identity
ModuleNotFoundError: No module named 'keystoneclient'
```

This can be addressed via exporting the library path from the snap

```diff
diff --git a/openstack/profiles/default b/openstack/profiles/default
index 8a8b9b7..aee252d 100755
--- a/openstack/profiles/default
+++ b/openstack/profiles/default
@@ -14,6 +14,8 @@ install_packages
 [[ -z "$FIP_RANGE" ]] && export FIP_RANGE="10.5.150.0:10.5.200.254"
 [[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="192.168.21.0/24"
 
+# [[ -z ${PYTHONPATH} ]] && export PYTHONPATH="/snap/openstackclients/current/lib/python3.6/site-packages"
+
 NS_ARG=""
 [ "`juju config neutron-api enable-ml2-dns`" = "true" ] && unset NAMESERVER || NS_ARG="-N $NAMESERVER"
```

However, this approach might lead to Python compatibility issues if the bastion uses a Python version other than 3.6.

The above patch also does not address the whole problem. When the model uses `vault` and `ssl`, the following exception is thrown:

```console
+ ./bin/neutron-ext-net-ksv3 --project admin --network-type flat -g 10.5.0.1 -c 10.5.0.0/16 -f 10.5.150.0:10.5.200.254 ext_net                                                                                     
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead                                                              
  from cryptography.utils import int_from_bytes                                                                                                                                                                    
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead                                                                  
  from cryptography.utils import int_from_bytes                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                 
  File "/snap/openstackclients/current/lib/python3.6/site-packages/urllib3/connectionpool.py", line 699, in urlopen                                                                                                
    httplib_response = self._make_request(                                                                                                                                                                         
  File "/snap/openstackclients/current/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request                                                                                          
    self._validate_conn(conn)                                                                                                                                                                                      
  File "/snap/openstackclients/current/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn                                                                                        
    conn.connect()                                                                                                                                                                                                 
  File "/snap/openstackclients/current/lib/python3.6/site-packages/urllib3/connection.py", line 411, in connect                                                                                                    
    self.sock = ssl_wrap_socket(                                                                                                                                                                                   
  File "/snap/openstackclients/current/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket                                                                                             
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)                                                                                                                                                    
  File "/snap/openstackclients/current/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl                                                                                       
    return ssl_context.wrap_socket(sock)                                                                                                                                                                           
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket                                                                                                                                                       
    return self.sslsocket_class._create(                                                                                                                                                                           
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create                                                                                                                                                          
    self.do_handshake()                                                                                                                                                                                            
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake                                                                                                                                                     
    self._sslobj.do_handshake()                                                                                                                                                                                    
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)                                                                     
```

If we can't fix this problem then we should add a note to the `README` stating that the `openstackclients` need to be installed via package.

**Comment by freyes** [comment]
Hi Nicolas,

The ssl certificate issue could be addressed if you set `OS_CACERT` to `/etc/ssl/certs/ca-certificates.crt`.

The reason why this is needed is that the archive's python3-certifi is patched to read from the system - https://salsa.debian.org/debian/python-certifi/-/blob/debian/master/debian/patches/0001-Use-Debian-provided-etc-ssl-certs-ca-certificates.cr.patch

Best,

**Comment by nicolasbock** [comment]
Thanks @freyes !
